version: '3'
services:
  qryn:
    image: qxip/qryn:latest
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse-server
      - CLICKHOUSE_AUTH=qryn:supersecretpassword
      - CLICKHOUSE_DB=qryn
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=qryn
      - CLICKHOUSE_PASSWORD=supersecretpassword
    ports:
      - 8123:8123
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', '127.0.0.1:8123/ping' ]
      interval: 1s
      timeout: 1s
      retries: 30

